### ISSUE TITLE
automatic sql table generation error

### ISSUE THREAD

**Issue by m3w88** [AmazingWikis/UserBoard#7]
- update.php fails to generate sql tables: Creating user_board table...RuntimeException from line 3232 of /mediawiki/includes/libs/rdbms/database/Database.php: Could not open "/mediawiki/extensions/UserBoard/includes/hooks/UserBoard/includes/sql/user_board.sql"

current workaround: manually adding the sql tables allows update.php to resolve
- special version throws `Error: Call to undefined method UserBoardHooks::onOutputPageBodyAttributes()`

**Comment by colleirose** [comment]
`onLoadExtensionSchemaUpdates` hook should be changed to this:

```php
    public static function onLoadExtensionSchemaUpdates( $updater ) {
        $dir = __DIR__;
        $db = $updater->getDB();
        $updater->addExtensionTable( 'user_board', "$dir/../sql/user_board.sql" );
    }
```
